---
title: "Temperature Loggers"
author: "Loay Jabre"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

This is a tesst to make sure the git is still working ( I played around with folders etc)
Date Last Editted: 
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
#this displays the date this file was written 
Sys.time()
```

Set Temperature: 2.5C    
Thermostat Position: Middle, air   
Logger 1: Air    
Logger 2: Water    
Comments: Logger 1&2 Calibrated (+0.2C to logger 1), thermostat calibrated (-0.5C)  

```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}
require(ggplot2)
require(dplyr)
require(plyr)
require(lubridate)
require(dplyr)
require(reshape2)
require(scales)
```

```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='hide'}
getwd()
dir()
````



```{r include=FALSE}
#this creates two strings for, one for each temperature logger. So, you enter file names here, and they are imported in the next chunk  
logger1 <- ("LJ_20180529_L1_1.csv")
logger2 <- ("LJ_20180529_L2_1_w.csv")

```

```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}
#Import the raw csv file from the temperature loggers
temp1raw = read.csv(logger1,  header = FALSE, sep =",")
temp2raw = read.csv(logger2, header = FALSE, sep =",")
```


```{r include=FALSE}
##Removing all the useless raw output from the logger
temp1 = temp1raw [-(1:200), -c(1,4, 5, 6)]
names(temp1)= c("time", "temperature1")

class(temp1$temperature1)
class(temp1$time)

##The logger exports the temperature as a factor. So, we need to convert it to a number. is a little more than just a as.numeric because the code was showing the wrong value at first. 
temp1$temperature1 = as.numeric(as.character(temp1$temperature1))

##This uses lubridate to convert the dates into a useable format. 
temp1$time = ymd_hms(temp1$time)

class(temp1$temperature1)
class(temp1$time)

#doing the same thing for the second temperature logger
temp2 = temp2raw [-(1:200), -c(1,4, 5, 6)]
names(temp2)= c("time2", "temperature2")
temp2$temperature2 = as.numeric(as.character(temp2$temperature2))
temp2$time2 = ymd_hms(temp2$time2)
```

```{r include=FALSE}
#Seperating the time into individual year, month, day etc. Don't really need it, but it could be usefull 
#watertemp1$year = format(watertemp1$time,"%Y")
#watertemp1$month = format (watertemp1$time, "%m")
#watertemp1$day = format (watertemp1$time, "%d")
#watertemp1$hour = format (watertemp1$time, "%H")
#watertemp1$minute = format (watertemp1$time, "%M")
```


```{r include=FALSE}
#This creates a new dataset called temp, with a common timeline and the two temperatures. 
temp3 = cbind(temp1, temperature2=temp2$temperature2)

temp = melt(data = temp3, id.vars = "time", measure.vars = c("temperature1", "temperature2"))

names(temp)= c("time", "logger", "temperature")

```


#Temperature 1   
```{r echo=FALSE}

boxplot(temp3$temperature1)


ggplot(data = temp3, aes(x=temperature1))+
geom_histogram(bins=30)+
theme_bw()+
xlab ("Temperature (C)")+
  ylab ("Frequency")+
  coord_cartesian(xlim=c(0,3))+
  ggtitle("Air Temperature")+
 theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))         
  

ggplot(temp3, aes(x=time, y=temperature1))+
  #the following line x=time assigns x and y axis labels
  geom_line()+
  coord_cartesian(ylim =c(0,3)) +
  scale_x_datetime(date_breaks = "1 hour",  labels = date_format("%m/%d - %H:%M")) +
  #theme_bw or _ whatever are just preset themes to help with making the graph look a certain way
  xlab ("Time")+
  ylab ("Temperature (C)")+
ggtitle("Air Temperature")+
 theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(axis.text.x = element_text(angle = 25, vjust = 1.0, hjust = 1.0)) 
  
  
#another way to play there "theme". Basically you control the way the gram looks
  #theme (panel.grid = element_blank(),
       # panel.background = element_rect(fill = "white"),
       # panel.border = element_rect(colour = "black", fill = NA,size = 0.2))
```

#Temperature 2   
```{r echo=FALSE}

#One thing that I need to do is learn to make loops. This way I am not repeating the same code for two different plots. 
boxplot(temp3$temperature2)



ggplot(data = temp3, aes(x=temperature2))+
geom_histogram(bins=20)+
xlab ("Temperature (C)")+
  ylab ("Frequency")+
  coord_cartesian(xlim=c(0,3))+
  ggtitle("Water Temperature")+
 theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))
  

ggplot(temp3, aes(x=time, y=temperature2))+
  geom_line()+
  coord_cartesian(ylim =c(0,3)) +
  scale_x_datetime(date_breaks = "1 hour",  labels = date_format("%m/%d - %H:%M")) +
  xlab ("Time")+
  ylab ("Temperature(C)")+
ggtitle("Water Temperature")+
 theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))+
    theme(axis.text.x = element_text(angle = 25, vjust = 1.0, hjust = 1.0)) 


```

```{r echo=FALSE}
#Both on the same line

##ggplot(data = temp, aes(x=logger, y=temperature))+
##geom_boxplot(notch = FALSE)+
##theme_bw()+
##xlab ("")+
##ylab ("Temperature (C)")


ggplot(temp, aes(x=time, y=temperature, colour = logger))+
  geom_line()+
  coord_cartesian(ylim =c(0,3)) +
  scale_x_datetime(date_breaks = "1 hour",  labels = date_format("%m/%d - %H:%M")) +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 25, vjust = 1.0, hjust = 1.0)) + 
  xlab ("Time")+
  ylab ("Temperature (C)") +
  theme(legend.position = "top")
```

